import { neon } from "@netlify/neon";
const sql = neon();

async function migrate() {
  console.log("Running Hospo migrations...");
  await sql(`CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, account_type TEXT NOT NULL CHECK (account_type IN ('worker','employer')), full_name TEXT, phone TEXT, date_of_birth DATE, county TEXT, profile_photo_url TEXT, onboarding_completed BOOLEAN DEFAULT FALSE, is_verified BOOLEAN DEFAULT FALSE, id_verification_status TEXT DEFAULT 'not_submitted', id_document_url TEXT, id_selfie_url TEXT, ppsn_encrypted TEXT, stripe_connect_account_id TEXT, stripe_connect_onboarded BOOLEAN DEFAULT FALSE, is_premium BOOLEAN DEFAULT FALSE, rating NUMERIC(3,2) DEFAULT 0, rating_count INTEGER DEFAULT 0, experience_years TEXT, skills TEXT[], bio TEXT, availability JSONB, max_travel_km INTEGER DEFAULT 25, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE TABLE IF NOT EXISTS venues (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, venue_type TEXT NOT NULL, address TEXT, town TEXT, county TEXT, eircode TEXT, phone TEXT, website TEXT, contact_email TEXT, logo_url TEXT, description TEXT, business_reg_number TEXT, stripe_connect_onboarded BOOLEAN DEFAULT FALSE, is_verified BOOLEAN DEFAULT FALSE, is_premium BOOLEAN DEFAULT FALSE, rating NUMERIC(3,2) DEFAULT 0, rating_count INTEGER DEFAULT 0, latitude NUMERIC(10,7), longitude NUMERIC(10,7), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE TABLE IF NOT EXISTS shifts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), venue_id UUID REFERENCES venues(id) ON DELETE CASCADE, role_type TEXT NOT NULL, shift_date DATE NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL, hourly_rate NUMERIC(6,2) NOT NULL, workers_needed INTEGER DEFAULT 1, description TEXT, skills_required TEXT[], requires_verified_id BOOLEAN DEFAULT TRUE, requires_own_transport BOOLEAN DEFAULT FALSE, requires_experience BOOLEAN DEFAULT FALSE, status TEXT DEFAULT 'available', applications_count INTEGER DEFAULT 0, assigned_to UUID REFERENCES users(id), assigned_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE TABLE IF NOT EXISTS shift_applications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), shift_id UUID REFERENCES shifts(id) ON DELETE CASCADE, worker_id UUID REFERENCES users(id) ON DELETE CASCADE, applicant_name TEXT, applicant_email TEXT, cover_note TEXT, status TEXT DEFAULT 'pending', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(shift_id, worker_id))`);
  await sql(`CREATE TABLE IF NOT EXISTS jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), venue_id UUID REFERENCES venues(id) ON DELETE CASCADE, job_title TEXT NOT NULL, role_type TEXT NOT NULL, employment_type TEXT DEFAULT 'part_time', description TEXT, salary_min NUMERIC(8,2), salary_max NUMERIC(8,2), location TEXT, county TEXT, skills_required TEXT[], experience_years TEXT, status TEXT DEFAULT 'open', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE TABLE IF NOT EXISTS job_applications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), job_id UUID REFERENCES jobs(id) ON DELETE CASCADE, worker_id UUID REFERENCES users(id) ON DELETE CASCADE, applicant_name TEXT, applicant_email TEXT, cover_letter TEXT, status TEXT DEFAULT 'pending', employer_notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(job_id, worker_id))`);
  await sql(`CREATE TABLE IF NOT EXISTS messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sender_id UUID REFERENCES users(id) ON DELETE CASCADE, recipient_id UUID REFERENCES users(id) ON DELETE CASCADE, sender_name TEXT, recipient_name TEXT, sender_email TEXT, recipient_email TEXT, content TEXT NOT NULL, read BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE TABLE IF NOT EXISTS ratings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), shift_id UUID REFERENCES shifts(id) ON DELETE CASCADE, rater_id UUID REFERENCES users(id), ratee_id UUID REFERENCES users(id), rater_type TEXT, stars INTEGER CHECK (stars BETWEEN 1 AND 5), feedback TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(shift_id, rater_id))`);
  await sql(`CREATE TABLE IF NOT EXISTS payments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), shift_id UUID REFERENCES shifts(id), worker_id UUID REFERENCES users(id), venue_id UUID REFERENCES venues(id), amount_cents INTEGER NOT NULL, platform_fee_cents INTEGER NOT NULL, worker_payout_cents INTEGER NOT NULL, status TEXT DEFAULT 'pending', stripe_payment_intent_id TEXT, paid_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE TABLE IF NOT EXISTS sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT UNIQUE NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW())`);
  await sql(`CREATE INDEX IF NOT EXISTS idx_shifts_venue ON shifts(venue_id)`);
  await sql(`CREATE INDEX IF NOT EXISTS idx_shifts_date ON shifts(shift_date)`);
  await sql(`CREATE INDEX IF NOT EXISTS idx_applications_shift ON shift_applications(shift_id)`);
  await sql(`CREATE INDEX IF NOT EXISTS idx_applications_worker ON shift_applications(worker_id)`);
  await sql(`CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)`);
  await sql(`CREATE INDEX IF NOT EXISTS idx_venues_owner ON venues(owner_id)`);
  console.log("All migrations complete!");
}

migrate().catch(err => { console.error("Migration failed:", err); process.exit(1); });
